name: Publish To Npm

on:
  release:
    types: [created]

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  lib-publish:
    name: Publish Lib
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: pnpm install  --force --no-frozen-lockfile
      - name: Run linter
        run: pnpm lint:email
      - name: Run tests
        run: pnpm test
      - name: Build Lib
        run: pnpm build
      - name: Publish package to npm registry
        run: cd ./packages/vue-email && pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
